intranet/gpao/urls.py
from django.conf.urls import patterns, url
 
urlpatterns = patterns('gpao.views',
        url(r'^$', 'main_gpao', name='main_gpao'),
        url(r'^nm/$', 'liste_nm', name='liste_nm'),
        url(r'^nm/(?P<no_nm>NM-\d{4}-\d{2})/$', 'details_nm', name='details_nm'),
        url(r'^nm/(?P<no_nm>NM-\d{4}-\d{2})/soumission$', 'soumission', name='soumission'),
        url(r'^pe/$', 'liste_pe', name='liste_pe'),
        url(r'^piece/$', 'liste_piece', name='liste_piece'),
        url(r'^piece/(?P<no_piece>\w{3}-\d{4}-\d{2})/$', 'details_piece', name='details_piece'),
        url(r'^famille/$', 'liste_famille', name='liste_famille'),
        url(r'^famille/(?P<famille>\w{3})/$', 'famille_piece', name='famille_piece'),
    )

intranet/intranet/urls.py
from django.conf.urls import *
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', 'intranet.views.index'),
                       url(r'^grappelli/', include('grappelli.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^accounts/', include('accounts.urls')),
                       url(r'^listesdeprix/', include('listes_de_prix.urls')),
                       url(r'^feuillesdetemps/', include('feuilles_de_temps.urls')),
                       url(r'^rapports/', include('rapports.urls')),
                       url(r'^gpao/', include('gpao.urls')),
                       url(r'^budget/', include('budget_materiel.urls')),
                       )

urlpatterns += staticfiles_urlpatterns()

intranet/gpao/models.py
#-*- coding: utf-8 -*-
import datetime
from operator import itemgetter

from django.db import models


class Famille(models.Model):
    reference = models.CharField(max_length=30, unique=True, verbose_name=u"# Référence:")
    designation = models.CharField(max_length=100, verbose_name=u"Désignation:")

    def __unicode__(self):
        return u"%s: %s" % (self.reference, self.designation)

    class Meta:
        ordering = ['reference']
        verbose_name = "Famille"
        verbose_name_plural = "Familles"


class Fournisseur(models.Model):
    nom = models.CharField(max_length=100, verbose_name=u"Nom:")

    def __unicode__(self):
        return u"%s" % self.nom


class Piece(models.Model):
    LETTER = 'LT'
    LEDGER = 'LD'
    A4 = 'A4'
    OTHER = 'OT'
    PAPER_FORMATS = (
        (LETTER, 'Letter'),
        (LEDGER, 'Ledger'),
        (A4, 'A4'),
        (OTHER, 'Autre'),
    )
    NONE = 'XX'
    ZINC = 'ZP'
    ANODISATION = 'AN'
    PEINT = 'PE'
    PLACAGE = 'PL'
    OXIDE_NOIR = 'OB'
    BROSSE = 'BR'
    AUTRE = 'OT'
    FINITIONS = (
        (NONE, 'Aucune'),
        (ZINC, 'Zinc Plated'),
        (ANODISATION, 'Anodisation'),
        (PEINT, 'Peint'),
        (PLACAGE, 'Placage'),
        (OXIDE_NOIR, 'Oxide Noir'),
        (BROSSE, 'Brossé'),
        (AUTRE, 'Autre'),
    )
    fournisseur = models.ForeignKey(Fournisseur, verbose_name=u"Fournisseur:", null=True, blank=True)
    famille = models.ForeignKey(Famille, verbose_name=u"Famille:")
    reference = models.CharField(max_length=30, unique=True, verbose_name=u"# Référence:")
    plan = models.FileField(upload_to="PLANS DE DEFINITION (X__-XXXX)", null=True, blank=True)
    designation = models.CharField(max_length=100, verbose_name=u"Désignation:")
    date = models.DateField(default=datetime.date.today, verbose_name=u"Date:")
    format_papier = models.CharField(max_length=2, choices=PAPER_FORMATS, default=LETTER,
                                     verbose_name=u"Format papier:")
    ref_commercial = models.CharField(max_length=30, verbose_name=u"Référence commercial:", default='XXX')
    ref_mecanique = models.CharField(max_length=30, verbose_name=u"Référence mécanique:", default='XXX')
    brute = models.CharField(max_length=30, verbose_name=u"Brute:", default='XXX')
    soudure = models.BooleanField(verbose_name=u"Soudure:", default=False)
    finition = models.CharField(max_length=2, choices=FINITIONS, default=NONE, verbose_name=u"Finition:")
    commentaires = models.CharField(max_length=200, verbose_name=u"Commentaires:", null=True, blank=True)
    prix = models.DecimalField(max_digits=6, decimal_places=2, verbose_name=u"Prix:", default=0.00)

    def __unicode__(self):
        return u"%s - %s" % (self.reference, self.designation)

    def get_nm(self):
        return LienPiece.objects.filter(to_piece=self)

    class Meta:
        ordering = ['reference']
        verbose_name = "Pièce"
        verbose_name_plural = "Pièces"


class Pe(models.Model):
    reference = models.CharField(max_length=30, unique=True, verbose_name=u"# Référence:")
    plan = models.FileField(upload_to="PLANS D'ENSEMBLE (PE-XXXX)")

    def __unicode__(self):
        return u"%s" % self.reference

    class Meta:
        ordering = ['reference']
        verbose_name = "Plan d'ensemble"
        verbose_name_plural = "Plan d'ensembles"


class Nm(models.Model):
    ASSY_SYSTEM = 'AS'
    WIRING_PNEUMATIC = 'WP'
    WIRING_ELECTRIC = 'WE'
    MACHINE = 'MA'
    SOFTWARE = 'SO'
    RETROFIT = 'RF'
    MODERNISATION = 'MO'
    REPARATION = 'RE'
    SETUP_CLAMP = 'SC'
    CATEGORIE_NM = (
        (ASSY_SYSTEM, 'Assy System'),
        (WIRING_PNEUMATIC, 'Wiring Pneumatic'),
        (WIRING_ELECTRIC, 'Wiring Electric'),
        (MACHINE, 'Machine'),
        (SOFTWARE, 'Software'),
        (RETROFIT, 'Rétrofit'),
        (MODERNISATION, 'Modernisation'),
        (REPARATION, 'Réparation'),
        (SETUP_CLAMP, 'Setup Clamp'),
    )
    reference = models.CharField(max_length=30, unique=True, verbose_name=u"# Référence:")
    pe = models.ForeignKey(Pe, null=True, blank=True, verbose_name=u"Plan d'ensemble:")
    designation = models.CharField(max_length=100, verbose_name=u"Désignation:")
    categorie = models.CharField(max_length=2, choices=CATEGORIE_NM, default=ASSY_SYSTEM,
                                 verbose_name=u"Catégorie de NM:")
    liens = models.ManyToManyField('self', through='LienNM', symmetrical=False, related_name='related_to',
                                   verbose_name=u"Contient les NMs suivant:")
    liens_piece = models.ManyToManyField(Piece, through='LienPiece', symmetrical=False, related_name='related_piece',
                                         verbose_name=u"Contient les Pièces suivante:")
    
    def __unicode__(self):
        return u"%s - %s" % (self.reference, self.designation)
        
    def get_liensnm(self):
        return LienNM.objects.filter(from_nm=self)
        
    def get_lienspiece(self):
        return LienPiece.objects.filter(from_nm=self).order_by('to_piece')

    def get_liste_nm(self):
        liste_nm = []

        for nm in self.get_liensnm():
            liste_nm.append({'nm': nm.to_nm, 'qt': nm.quantite, })
            if nm.to_nm.get_liensnm():
                nms_temp = nm.to_nm.get_liste_nm()
                for nm in nms_temp:
                    temp = next((item for item in liste_nm if item == liste_nm), None)
                    if not temp:
                        liste_nm.append({'nm': nm['nm'], 'qt': nm['qt'], })
                    else:
                        temp['qt'] += nm['qt']
        return liste_nm

    def get_liste_piece_self(self):
        liste_piece = []
        for piece in self.get_lienspiece():
            liste_piece.append({'ref': piece.to_piece.reference, 'piece': piece.to_piece, 'qt': piece.quantite, })

        return liste_piece

    def get_pieces_list(self):
        liste_nm = self.get_liste_nm()
        part_list = self.get_liste_piece_self()
        for nm in liste_nm:
            liste_piece = nm['nm'].get_liste_piece_self()
            for piece in liste_piece:
                temp = next((item for item in part_list if item['piece'] == piece['piece']), None)
                if not temp:
                    part_list.append(piece)
                else:
                    temp['qt'] += piece['qt']
        return part_list

    # def get_pieces_list(self):
    #     pieces = []
    #
    #     for p in self.get_lienspiece():
    #         pieces.append(p.to_piece.reference)
    #
    #     if self.get_liensnm() is not None:
    #         for nm in self.get_liensnm():
    #             if nm.to_nm.get_liensnm():
    #                 pieces_temp = nm.to_nm.get_pieces_list()
    #                 for piece in pieces_temp:
    #                     temp = next((item for item in pieces if item == piece), None)
    #                     if not temp:
    #                         pieces.append(piece)
    #             else:
    #                 for p in nm.to_nm.get_lienspiece():
    #                     temp = next((item for item in pieces if item == p.to_piece.reference), None)
    #                     if not temp:
    #                         pieces.append(p.to_piece.reference)
    #     return pieces

    def get_pieces(self):
        pieces = []
        total = 0
        for p in self.get_lienspiece():
            pieces.append({'ref': p.to_piece.reference, 'piece': p.to_piece, 'qt': p.quantite,
                           'fournisseur': p.to_piece.fournisseur.nom, 'prix': p.to_piece.prix * p.quantite,
                           'total': total})

        if self.get_liensnm() is not None:
            for nm in self.get_liensnm():
                multi = nm.quantite
                if nm.to_nm.get_liensnm():
                    pieces_temp = nm.to_nm.get_pieces()
                    for piece in pieces_temp:
                        piece['qt'] *= multi
                        temp = next((item for item in pieces if item['piece'] == piece['piece']), None)
                        if temp:
                            temp['qt'] += piece['qt']
                            temp['prix'] += piece['prix']
                        else:
                            pieces.append(piece)
                else:
                    for p in nm.to_nm.get_lienspiece():
                        temp = next((item for item in pieces if item['piece'] == p.to_piece), None)
                        if temp:
                            temp['qt'] += (p.quantite * multi)
                            temp['prix'] += p.to_piece.prix * p.quantite
                        else:
                            total += p.to_piece.prix * p.quantite
                            pieces.append({'ref': p.to_piece.reference, 'piece': p.to_piece,
                                           'qt': (p.quantite * multi), 'fournisseur': p.to_piece.fournisseur.nom,
                                           'prix': p.to_piece.prix * p.quantite, 'total': total})
        for piece in pieces:
            total += piece['prix']
            piece['total'] = total
        return sorted(pieces, key=itemgetter('fournisseur', 'ref'))

    class Meta:
        ordering = ['reference']
        verbose_name = "Nomenclature"
        verbose_name_plural = "Nomenclatures"


class LienNM(models.Model):
    from_nm = models.ForeignKey(Nm, related_name='from_nm')
    to_nm = models.ForeignKey(Nm, related_name='to_nm', verbose_name=u"Lié à NM:")
    numero_pe = models.IntegerField(verbose_name=u"# sur le PE:")
    quantite = models.IntegerField(verbose_name=u"Quantité:")
    
    def __unicode__(self):
        return u"%s linkto %s" % (self.from_nm, self.to_nm)


class LienPiece(models.Model):
    from_nm = models.ForeignKey(Nm, related_name='from_nm_p')
    to_piece = models.ForeignKey(Piece, related_name='to_piece', verbose_name=u"Lié à Pièce:")
    numero_pe = models.IntegerField(verbose_name=u"# sur le PE:")

intranet/gpao/forms.py
from django import forms
from gpao.models import *
from django.forms.formsets import formset_factory


class PieceSoumissionForm(forms.Form):
    choix = forms.BooleanField(required=False)
    piece = forms.ModelChoiceField(queryset=Piece.objects.all())
    qt = forms.IntegerField()

SoumissionFormset = formset_factory(PieceSoumissionForm, extra=0)

intranet/gpao/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from gpao.models import Nm, Pe, Piece, Famille
from gpao.forms import *
from operator import itemgetter


def main_gpao(request):
    return render(request, "gpao/main_gpao.html")


def liste_nm(request):
    liste_nm = Nm.objects.all().order_by('reference')
    return render(request, "gpao/liste_nm.html", {'liste_nm': liste_nm})


def details_nm(request, no_nm):
    nm = Nm.objects.get(reference=no_nm)
    return render(request, "gpao/details_nm.html", {'nm': nm})


def liste_pe(request):
    liste_pe = Pe.objects.all().order_by('reference')
    return render(request, "gpao/liste_pe.html", {'liste_pe': liste_pe})


def liste_piece(request):
    liste_piece = Piece.objects.all().order_by('famille', 'reference')
    return render(request, "gpao/liste_piece.html", {'liste_piece': liste_piece})


def liste_famille(request):
    liste_famille = Famille.objects.all().order_by('reference')
    return render(request, "gpao/liste_famille.html", {'liste_famille': liste_famille})


def famille_piece(request, famille):
    pieces = Piece.objects.filter(famille__reference = famille)
    return render(request, "gpao/famille_piece.html", {'pieces': pieces})


def details_piece(request, no_piece):
    piece = Piece.objects.get(reference=no_piece)
    return render(request, "gpao/details_piece.html", {'piece': piece})


def soumission(request, no_nm):
    nm = Nm.objects.get(reference=no_nm)
    formset_init = []
    liste_qt = nm.get_pieces_list()
    #liste_qt = sorted(liste_qt, key=itemgetter('ref'))
    for piece in liste_qt:
        formset_init.append({'choix': False, 'piece': piece['piece'].id, 'qt': piece['qt']})

    if request.method == 'POST':  # If the form has been submitted...
        formset = SoumissionFormset(request.POST)
        if formset.is_valid():  # All validation rules pass
            return render(request, 'gpao/demandesoumission.html', {'formset': formset, 'no_nm': no_nm, })
    else:
        formset = SoumissionFormset(initial=formset_init)

    return render(request, 'gpao/soumission.html', {'formset':formset, 'no_nm': no_nm, })

intranet/templates/gpao/demandesoumission.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>GEI | GPAO</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Le styles -->
    <link href="{{STATIC_URL}}css/bootstrap.css" rel="stylesheet">
	<style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
	  }
    </style>
    <link href="{{STATIC_URL}}css/bootstrap-responsive.css" rel="stylesheet" >
	<link href="{{STATIC_URL}}css/extra.css" rel="stylesheet" >
	<script type="text/javascript" src="{{STATIC_URL}}js/bootstrap.js"></script>
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

</head>
<body>
<div class="container-fluid">
<div class="well">
    <div class="row-fluid">
        <div class="span12">
            <h4 style='text-align:right'>Demande de Soumission</h4>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div style='float: left;margin-top: 40px;' >
            <pre>
DE:    EUGÉNIE CANADA INC.
       3382 Jacob-Jordan
       Terrebonne, Qc. J6X 4J6

       Tél: 450-313-1321</pre>
            </div>
            <img style='float: right;' src='{{ STATIC_URL }}img/logo_eugenie.png' />
       </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
        <pre style='float: right;margin-top: -60px;'>
DATE...........: {% now "SHORT_DATE_FORMAT" %}
NO. DE PROJET..: {{ no_nm }}</pre>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span12">
                <table style='background-color: rgba(255, 255, 255, 0)' width='100%' border="0">
                    <thead>
                        <tr style="border-bottom: solid black 1px">
                            <th>Quantité</th>
                            <th>Pièces</th>
                            <th>Prix</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% load gpao_filters %}
                        {% for form in formset %}
                            {% if form.choix.value == True %}
                            <tr>
                                <td style="text-align: center">{{ form.qt.value }}</td>
                                <td>{{ form.piece.value|get_piece_display }}</td>
                                <td style="text-align: center">..................$</td>
                            </tr>
                            {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
        </div>
    </div>
</div></div>
</body>
</html>

intranet/templates/gpao/details_nm.html
{% extends "base.html" %}
{% load admin_urls %}
{% load humanize %}
{% block title %}GPAO{% endblock title %}
{% block nav-gpao %}<li class="dropdown active">{% endblock nav-gpao %}
{% block content %}
    <div class="row-fluid">
        <div class="span8 offset2">
            <div class="well">
                <div class="row-fluid">
                    <div class="pull-left">
                        <h4>GPAO</h4>
                        <h4>{{nm.reference}} {{nm.designation}}</h4>
                    </div>
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{% url 'admin:gpao_nm_change' nm.id %}">Modifier la NM</a>
                    </div>
                </div>
                <div class="row-fluid">
                    <h5>Plan d'ensemble lié: <a href="{{ nm.pe.plan.url }}">{{nm.pe}}</a></h5>
                    <h5 class="text-center">NMs et Pièces liés</h5>
                    <table class="table table-striped table-bordered table-condensed">
                        <thead>
                            <tr>
                                <th>N° sur PE</th>
                                <th>Référence</th>
                                <th>Désignation</th>
                                <th>Qt.</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for lien in nm.get_liensnm %}
                                <tr>
                                    <td>{{lien.numero_pe}}</td>
                                    <td><a href="{% url 'details_nm' lien.to_nm.reference %}">{{lien.to_nm.reference}}</a></td>
                                    <td>{{lien.to_nm.designation}}</td>
                                    <td>{{lien.quantite}}</td>
                                </tr>
                            {% endfor %}
                            {% for piece in nm.get_lienspiece %}
                                <tr>
                                    <td>{{piece.numero_pe}}</td>
                                    <td><a href="{% url 'details_piece' piece.to_piece.reference %}">{{piece.to_piece.reference}}</a></td>
                                    <td>{{piece.to_piece.designation}}</td>
                                    <td>{{piece.quantite}}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="row-fluid">
                    <div class="pull-right">
                        <a target='_blank' class='btn btn-primary' href="{% url 'soumission' nm.reference %}">Faire une soumission</a>
                    </div>
                    <h5 class="text-center">NMs et Pièces liés</h5>
                    <table class="table table-striped table-bordered table-condensed">
                        <tr>
                            <th>Pièces</th>
                            <th>Fournisseur</th>
                            <th>Prix unitaire</th>
                            <th>Quantité</th>
                            <th>Prix</th>
                        </tr>
                        {% for pieces in nm.get_pieces %}
                            <tr>
                                <td>{{ pieces.piece }}</td>
                                <td>{{ pieces.fournisseur }}</td>
                                <td>{{ pieces.piece.prix }}&nbsp;$</td>
                                <td>{{ pieces.qt }}</td>
                                <td style="text-align: right;">{{ pieces.prix }}&nbsp;$</td>
                            </tr>
                            {% if forloop.last %}
                                <tr>
                                    <th style="text-align: right;background-color: lightgray" colspan="3"></th>
                                    <th style="text-align: right;background-color: lightgray">Total:</th>
                                    <td style="text-align: right;background-color: lightgray">{{pieces.total}}&nbsp;$</td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

intranet/templates/gpao/details_piece.html
{% extends "base.html" %}
{% load admin_urls %}
{% block title %}GPAO{% endblock title %}
{% block nav-gpao %}<li class="dropdown active">{% endblock nav-gpao %}
{% block content %}
    <div class="row-fluid">
        <div class="span6 offset3">
            <div class="well">
                <div class="row-fluid">
                    <div class="pull-left">
                        <h4>GPAO</h4>
                        <h4>{{piece.reference}} {{piece.designation}}</h4>
                    </div>
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ piece.plan.url }}">Plan de définition</a>
                        <a class="btn btn-primary" href="{% url 'admin:gpao_piece_change' piece.id %}">Modifier la pièce</a>
                    </div>
                </div>
                <div class="row-fluid">
                    <p>Date: {{piece.date}}</p>
                    <p>Format papier: {{piece.get_format_papier_display}}</p>
                    <p>Réf. commerciale: {{piece.ref_commercial}}</p>
                    <p>Réf. mécanique: {{piece.ref_mecanique}}</p>
                    <p>Brute: {{piece.brute}}</p>
                    <p>Soudure: {% if piece.soudure %}Oui{% else %}Non{% endif %}</p>
                    <p>Finition: {{piece.get_finition_display}}</p>
                    <p>Commentaires: {{piece.commentaires}}</p>

                    <h5 class="text-center">Cette pièce se retrouve dans les NMs suivant:</h5>
                    <table class="span8 offset2 table table-striped table-bordered table-condensed">
                        <thead>
                            <tr>
                                <th>Référence</th>
                                <th>Désignation</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for lien in piece.get_nm %}
                                <tr>
                                    <td><a href="">{{lien.from_nm.reference}}</a></td>
                                    <td>{{lien.from_nm.designation}}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

intranet/templates/gpao/famille_piece.html
{% extends "base.html" %}
{% block title %}GPAO{% endblock title %}
{% block extrahead %}
<script type="text/javascript" language="javascript" src="{{STATIC_URL}}TableFilter/tablefilter.js"></script>
{% endblock extrahead %}
{% block nav-gpao %}<li class="dropdown active">{% endblock nav-gpao %}
{% block content %}
    <div class="row-fluid">
        <div class="span8 offset2">
            <div class="well">
                <h4>GPAO</h4>
                <h4>LISTE DES PIÈCES DE LA FAMILLE {{pieces.0.famille}}</h4>
                <table id="table1" class="filterable table table-striped table-bordered table-condensed">
                    <thead>
                        <tr>
                            <th>Référence & Révision</th>
                            <th>Désignation</th>
                            <th>Réf. commerciale</th>
                            <th>Réf. mécanique</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for piece in pieces %}
                            <tr>
                                <td><a href="">{{piece.reference}}</a> <a href="{{ piece.plan.url }}">(Plan de déf.)</a></td>
                                <td>{{piece.designation}}</td>
                                <td>{{piece.ref_commercial}}</td>
                                <td>{{piece.ref_mecanique}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

intranet/templates/gpao/liste_famille.html
{% extends "base.html" %}
{% block title %}GPAO{% endblock title %}
{% block nav-gpao %}<li class="dropdown active">{% endblock nav-gpao %}
{% block content %}
    <div class="row-fluid">
        <div class="span4 offset4">
            <div class="well">
                <h4>GPAO</h4>
                <h4>LISTE DES FAMILLES DE PIÈCE</h4>
                <table class="table table-striped table-bordered table-condensed">
                    <thead>
                        <tr>
                            <th>Référence</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for famille in liste_famille %}
                            <tr>
                                <td><a href="{% url 'famille_piece' famille.reference %}">{{famille}}</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

intranet/templates/gpao/liste_nm.html
{% extends "base.html" %}
{% block title %}GPAO{% endblock title %}
{% block extrahead %}
<script type="text/javascript" language="javascript" src="{{STATIC_URL}}TableFilter/tablefilter.js"></script>
{% endblock extrahead %}
{% block nav-gpao %}<li class="dropdown active">{% endblock nav-gpao %}
{% block content %}
    <div class="row-fluid">
        <div class="span8 offset2">
            <div class="well">
                <div class="pull-left">
                    <h4>GPAO</h4>
                    <h4>RÉFÉRENCEMENT DES NOMENCLATURES</h4>
                </div>
                <div class="pull-right">
                    <a class="btn btn-primary" href="{% url 'admin:gpao_nm_add' %}">Ajouter un NM</a>
                </div>
                <table id="table1" class="filterable table table-striped table-bordered table-condensed">
                    <thead>
                        <tr>
                            <th>Référence & Révision</th>
                            <th>Plan d'ensemble liés</th>
                            <th>Désignation</th>
                            <th>Référence</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for nm in liste_nm %}
                            <tr>
                                <td><a href="{% url 'details_nm' nm.reference %}">{{nm.reference}}</a></td>
                                <td><a href="{{nm.pe.plan.url}}">{{nm.pe}}</a></td>
                                <td>{{nm.designation}}</td>
                                <td>{{nm.get_categorie_display}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

intranet/templates/gpao/liste_pe.html
{% extends "base.html" %}
{% block title %}GPAO{% endblock title %}
{% block nav-gpao %}<li class="dropdown active">{% endblock nav-gpao %}
{% block content %}
    <div class="row-fluid">
        <div class="span6 offset3">
            <div class="well">
                <h4>GPAO</h4>
                <h4>RÉFÉRENCEMENT DES PLANS D'ENSEMBLE</h4>
                <table class="table table-striped table-bordered table-condensed">
                    <thead>
                        <tr>
                            <th>Référence & Révision</th>
                            <th>Nomenclatures liés</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for pe in liste_pe %}
                            <tr>
                                <td><a href="{{pe.plan.url}}">{{pe.reference}}</a></td>
                                <td>{% for nm in pe.nm_set.all %}<a href="{% url 'details_nm' nm.reference %}">{{nm}}, </a><br />{% endfor %}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

intranet/templates/gpao/main_gpao.html
{% extends "base.html" %}
{% block title %}GPAO{% endblock title %}
{% block nav-gpao %}<li class="dropdown active">{% endblock nav-gpao %}
{% block content %}
    <div class="row-fluid">
        <div class="span4 offset4">
            <div class="well">
                <h4>GPAO</h4>
                <ul>
                    <a href="{% url 'liste_nm' %}"><li>RÉFÉRENCEMENT DES NOMENCLATURES</li></a>
                    <a href="{% url 'liste_pe' %}"><li>RÉFÉRENCEMENT DES PLANS D'ENSEMBLES</li></a>
                    <a href="{% url 'liste_famille' %}"><li>LISTE DES FAMILLES DE PIÈCE</li></a>
                    <a href="{% url 'liste_piece' %}"><li>LISTE DES PIÈCES</li></a>
                </ul>
	        </div>
        </div>
    </div>
{% endblock %}